### ISSUE TITLE
TODO: Skin updater

### ISSUE THREAD

**Issue by SirDavidLudwig** [ForgeTheory/InterCraftWebsite#8]
A Python script is needed to run periodically to update the skins of the players.

**Comment by SirDavidLudwig** [comment]
Required images:
- Raw Skin (Standard Size)
- Face (120x120)

**Comment by cloostefis** [comment]
There will be two scripts. The first one is a python script that does the bulk of the work downloading and processing. The second one is a helper shell script that adds the python script to the crontab.

The python script will:

* Save skins to `public/assets/skins/<uuid>.png`
* Crop and scale the face, and save to `public/assets/skins/<uuid>-face.png`
* Update all skins if no parameters are given.
* Update one specified skin.

**Comment by cloostefis** [comment]
On second thought, you'll have to add it to the crontab yourself. It's not hard. I'll include some documentation with the script.

**Comment by cloostefis** [comment]
Finished.
